[package]
name = "exact-versions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cr1 = { path = "cr1" }
cr2 = { path = "cr2" }

[workspace]
members = [
    "cr1",
    "cr2",
]